# Generated by Django 2.0.7 on 2018-08-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDapp', '0003_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
